spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/menudb
    username: ohgiraffers
    password: ohgiraffers

# MyBatis confiuration
mybatis:
  mapper-locations: mapper/**/*.xml
